urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search', views.SearchTripView.as_view(), name='search'),
    url(r'^trip/(?P<trip>\d+)/select_seat', views.SelectSeatView.as_view(), name='select_seat'),
    url(r'^confirm_ticket$', views.ConfirmTicketView.as_view(), name='confirm_ticket'),

    url(r'^edit_route/(\d+)', views.EditRoute.as_view(), name='edit_route'),
    url(r'^manage_routes', views.ManageRoutes.as_view(), name='manage_routes'),
    url(r'^delete_route/(?P<pk>\d+)', views.DeleteRoute.as_view(), name='delete_route'),

    url(r'^manage_trips', views.ManageTrips.as_view(), name='manage_trips'),
    url(r'^add_trip/route/(?P<route>\d+){0,1}$', views.AddTripView.as_view(), name='add_trip'),
    url(r'^update_trip/(?P<pk>\d+)$', views.ChangeTripView.as_view(), name='update_trip'),

    url(r'^admin/report/trip/(?P<trip_id>\d+)', views.TripReportView.as_view(), name='trip_report'),


    url(r'^route/(?P<route>\d+)/delete_node/(?P<pk>\d+)/$',
        views.DeleteNode.as_view(), name='delete_node'),
    url(r'^route/(?P<route>\d+)/update_node/(?P<pk>[\d]+)/$',
        views.UpdateNode.as_view(), name='update_node'),
    url(r'^thanks', views.ThanksView.as_view(), name='thanks')
]

forms.py
from django import forms
from models import RouteNode, Trip, Station, Ticket


class PurchaseTicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('customer_first_name', 'customer_last_name', 'email', 'bed', 'tea')


class RouteNodeForm(forms.ModelForm):
    def __init__(self, **kwargs):
        super(RouteNodeForm, self).__init__(**kwargs)
        self.fields['arrival'].required = False
        self.fields['departure'].required = False

    class Meta:
        model = RouteNode
        fields = [
            'route',
            'station',
            'arrival',
            'departure',
            'duration',
        ]
        widgets = {
            'arrival': forms.TextInput(attrs={'class': 'timepicker'}),
            'departure': forms.TextInput(attrs={'class': 'timepicker'}),
            'duration': forms.TextInput(attrs={'class': 'duration-timepicker'}),
        }

    # TODO override save method to validate duration
        # TODO check not null arrival and departure
        # TODO don't allow same stations


# TODO maybe combine next together with separating only admin field
# TODO or maybe inherit on from another
class TripSearchForm(forms.Form):
    # TODO in future this fields must be text inputs, pulling stations dynamically
    from_where = forms.ChoiceField(choices=((x.id, x.name) for x in Station.objects.all()))
    to_where = forms.ChoiceField(choices=((x.id, x.name) for x in Station.objects.all()))
    date = forms.DateField(label='Date')


# for admin pages
class FilterTripForm(forms.Form):
    include_completed = forms.BooleanField(label='Include completed', initial=False, required=False)
    show_before = forms.DateField(required=False)
    show_after = forms.DateField(required=False)

templates/admin_base.html
{% extends 'base.html' %}
{% block nav %}
    {% include "admin_nav.html" %}
{% endblock %}

templates/admin_edit_route.html
{% extends 'admin_base.html' %}

{% block content %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script>
        $(document).ready(function () {
            $('input.timepicker').timepicker({
                timeFormat: 'HH:mm',
                interval: 15,
                dynamic: false,
                dropdown: true,
                scrollbar: true
            });
        });
    </script>

    <h2>Route #{{ route.id }}</h2>

    <table class="table existing-route-nodes">
        <thead>
        <tr>
            <th>Station</th>
            <th>Arrival</th>
            <th>Departure</th>
            <th>Duration</th>
        </tr>
        </thead>
        <tbody>
        {% for node in nodes %}
            <tr id="row-routenode-{{ node.id }}">
                <td>{{ node.station.name }}</td>
                <td class="cell-arrival"
                    data-value="{{ node.arrival|time:"H:i" }}">{{ node.arrival|time:"H:i" }}</td>
                <td class="cell-departure"
                    data-value="{{ node.departure|time:"H:i" }}">{{ node.departure|time:"H:i" }}</td>
                <td>{{ node.duration }}</td>
                <td><a href="{% url 'update_node' route.id node.id %}">edit</a></td>
                <td><a href="{% url 'delete_node' route.id node.id %}">delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <form method="post">
        <div class="col-6">
            {% csrf_token %}
            {% include 'form_snippet.html' %}
            <input type="submit" value="Save route node">
        </div>
    </form>

{% endblock %}

templates/admin_manage_routes.html
{% extends 'admin_base.html' %}
{% block content %}
<table class="table">
    <thead>
        <th>#</th>
        <th>Description</th>
    </thead>
    <tbody>
    {% for route in routes %}
        <tr>
            <td>{{ route.id }}</td>
            <td>
                <div>
                    <p>
                    {{ route.description }}
                    </p>

                </div>
            </td>
            <td>
                <button type="button"
                        class="btn btn-info"
                        data-toggle="collapse"
                        data-target="#routenodes{{ route.id }}"
                        aria-expanded="false" aria-controls="routenodes{{ route.id }}"
                >
                    Stations
                </button>
                <div class="collapse" id="routenodes{{ route.id }}">
                    <ul >
                        {% for rn in route.routenode_set.reverse %}
                        <li>{{ rn }}</li>
                        {% endfor %}
                    </ul>
                </div>

            </td>
            <td><a href="edit_route/{{ route.id }}">edit route</a></td>
            <td><a href="delete_route/{{ route.id }}">delete route</a></td>

            <td><a href="{% url 'add_trip' route.id %}">create trip</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<form method="post">
    {% csrf_token %}
{#    <label>ID</label>#}
{#    <input name="id">#}
    <label>Desc</label>
    <input name="description">
    <input type="submit" value="yeah">
</form>
{% endblock %}

templates/admin_manage_trips.html
{% extends 'admin_base.html' %}

{% block content %}
    {% block local_script %}
    <script>

        function setCompleted(trip_id){
            var url = 'update_trip/'
            $.post(url+trip_id,
                {
                    id:trip_id,
                    completed:true,
                },'json')
                .done(function(response){
                    $('#row-trip-'+trip_id).remove();
                    alert('Trip set completed.');
                })
        }

        function setCancelled(trip_id){
            $.post({id:trip_id})
                .done(function(response){
                    alert('done');
                })
        }
    </script>
{% endblock %}
<form class="form">
    {{ filter_form.as_ul  }}
    <input type="submit">
</form>

<table class="table">
    <thead>
        <th>Route</th>
        <th>Departure</th>
        <th>Arrival</th>
    </thead>
    <tbody>
    {% for trip in object_list %}
        <tr id="row-trip-{{ trip.id }}">
            <td>{{ trip.route }}</td>
            <td>{{ trip.date_departure }}</td>
            <td>{{ trip.date_arrival }}</td>
            <td><button class="btn btn-outline-success"
                        role="button"
                        {% if trip.completed %} disabled="disabled" {% endif %}
                        onclick="setCompleted({{ trip.id }});">complete</button></td>
            <td><button class="btn btn-outline-danger"
                        role="button"
                        onclick="setCancelled({{ trip.id }});">cancel</button></td>
            <td><a href="{% url 'trip_report' trip.id %}">Report</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<a class="btn btn-primary"
   href="{% url 'add_trip'%}">
    Add another
</a>

{% endblock %}

templates/admin_nav.html
<ul class="list-inline">
    <li class="list-inline-item">
        <span>Administrating</span>
    </li>
    <li class="list-inline-item">
        <a href="{% url 'manage_routes' %}">
            Routes
        </a>
    </li>
    <li class="list-inline-item">
        <a href="{% url 'manage_trips' %}">
            Trips
        </a>
    </li>
    <li class="list-inline-item">
        <a href="{% url 'trip_report' 1%}">
            Report
        </a>
    </li>
{#    <li>#}
{#        <a href="{% url %}">#}
{##}
{#        </a>#}
{#    </li>#}

</ul>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tickets Purchase service</title>
    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'tickets/css/main.css' %}">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          crossorigin="anonymous">
    <script src="{% static 'csrf.js' %}"></script>
    {% block statics %}
    {% endblock %}
</head>
<body>
{% block heading %}
    <h2> Welcome to Orgalorg</h2>
{% endblock %}
{% block nav %}
{% endblock %}
{#    <div id="container" class="container">#}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/form_snippet.html
{% load widget_tweaks %}

{# Include the hidden fields #}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{# Include the visible fields #}
{% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }} {{ field|add_class:"form-control"  }}
    </div>
{% endfor %}

templates/search_trains.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block statics %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script>
        $(document).ready(function(){
            $('input#id_date').datepicker();
        })
    </script>
{% endblock %}
{% block content %}
    <div>
        <div>
            <form class="form-inline">
                {% include "form_snippet.html" %}
                <button class="btn">Submit</button>
            </form>
        </div>
        <div>
            <table class="table">
                <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Desc
                    </th>
                    <th>
                        Departure:
                    </th>
                    <th>
                        Arrival:
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for result in object_list %}
                    <tr>
                        <td>
                            {{ result.route.id }}
                        </td>
                        <td>
                            {{ result.route.description }}
                        </td>
                        <td>
                            {{ result.d_time|date:"Y/m/d H:i" }}
                        </td>
                        <td>
                            {{ result.a_time|date:"Y/m/d H:i" }}
                        </td>
                        <td>
                            <a href="{% url 'select_seat' result.id %}?from={{ request.GET.from_where }}&to={{ request.GET.to_where }}">Select
                                seat</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/select_seat.html
{% extends 'base.html' %}
{% load static %}

{% block statics %}
    <link rel="stylesheet" href="{% static 'tickets/css/select_seat.css' %}">
{% endblock %}

{% block content %}
    <div>
        <h2>Route # {{ trip.route.id }} {{ trip.route.routenode_set.last }} - {{ trip.route.routenode_set.first }}</h2>
    </div>
    <div>
        <span> <b>From:</b></span>
        <span>{{ station_from.name }}</span>
        <span><b>To:</b></span>
        <span>{{ station_to.name }}</span>
    </div>
    <div class="list-group" id="accordion" role="tablist">
        {% for car_num, car_info in available_seats.items %}
            {% include "tickets/wagon_widget.html" %}
        {% endfor %}
    </div>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<p>Let's pretend that you paid for your ticket ;)</p>
<p>Thank you, have a great day!</p>
{% endblock %}

templates/ticket_form.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div>
            <label>Train: </label>
            <span>{{ ticket.trip.route }}</span>
        </div>
        <div>
            <label>Departure: </label>
            <span>{{ ticket.boarding_station }}</span>
        </div>
        <div>
            <label>Arrival: </label>
            <span>{{ ticket.destination_station }}</span>
        </div>
        <div>
            <label>Departure time: </label>
            <span>{{ ticket.date_departure }}</span>
        </div>
        <div>
            <label>Arrival time: </label>
            <span>{{ ticket.date_arrival }}</span>
        </div>

        <div>
            <label>Cost: </label>
            <span>$</span><span>{{ ticket.cost }}</span>
        </div>

    </div>
    <div class="form-group">
        <form method="post">
            {% csrf_token %}
            <ul>
                {{ form.as_p }}
            </ul>
            {{ form.errors }}
            <input type="submit">
        </form>
    </div>
{% endblock %}